### ISSUE TITLE
[Feature request] change of spheric resolution or bend polygon around sphere

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-conic-polygon-geometry#2]
The conic-polygon-geometry only uses border coords, it works fine for small regions. But for big regions, it makes large flat areas which will be blocked by the sphere surface:

with 0 altitude, only borders are visible for most regions
![Screen Shot 2020-07-15 at 20 18 06](https://user-images.githubusercontent.com/3398981/87606173-e6081800-c72c-11ea-98be-68c5036ae3e3.png)
with 0.1 altitude, more visible regions, but still holes for big countries
![Screen Shot 2020-07-15 at 20 18 48](https://user-images.githubusercontent.com/3398981/87606179-ea343580-c72c-11ea-854c-1eee8202c925.jpg)

The idea would be adding vertices in the middle of regions, especially for big regions, then bend around the globe, finally something like:
![](https://i.stack.imgur.com/zeuEQ.png)

It will be very nice if the vertices/triangulated map can be done automatically!

**Comment by vasturiano** [comment]
@lslzl3000 thanks for filing this issue.

It made me dig deeper into how to make the surfaces more curved by fragmenting the surface faces into smaller ones so that it increasingly approximates a sphere.
I ended up triangulating these cases using [delaunator](https://github.com/mapbox/delaunator) instead of [earcut](https://github.com/mapbox/earcut) which only uses the polygons contour.

The spheric angular resolution (in degrees) can be configured using the `curvatureResolution` parameter.

Result: https://vasturiano.github.io/three-conic-polygon-geometry/example/countries/
